name: deploy_to_dev

concurrency: 1

on:
  workflow_dispatch

env:
  DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
  DATABRICKS_BUNDLE_ENV: dev

jobs:
  deploy:
    environment: dev
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: |
          databricks bundle validate -t "dev" --profile dev

      - run: |
          databricks bundle deploy -t "dev" --profile dev
         
